# Site
name: 'tcgua.com'
description: 'we love magic'
logo: 'assets/images/U.svg'
favicon: 'assets/images/U.ico'
baseurl: ''
disqus: 'tcgua'
email: 'oleg.chorny@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
authors:
    oleg:
      name:           Oleg
      site:           https://tcgua.com
      avatar:         assets/images/avatar1.jpg
      bio:            "mtg for fun and not for profit"
      email:          oleg.chorny@gmail.com
      twitter:        https://twitter.com/olegchorny
    judge:
      name:           Judge
      site:           https://tcgua.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Level 1 Judge"
      email:          judge@fake.com
      twitter:        https://twitter.com/judge
    zvi:
      name:           Zvi
      site:           https://tcgua.com
      avatar:         assets/images/avatar1.jpg
      bio:            "Just playing the game"
      email:          od.webcoder@gmail.com
      twitter:        "#"
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: oleg
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

kramdown:
  parse_span_html: true

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]